<#
  idf-build.ps1 - build (and flash) NAV-1 with ESP-IDF 5.5.4 + arduino-esp32 as a component (idf\).
  Sources in firmware\, system settings in idf\sdkconfig.defaults. ESP-IDF 5.5.4: set IDF_PATH or install it at C:\esp\esp-idf-v5.5.4.

    .\idf-build.ps1                  # compile
    .\idf-build.ps1 -Upload          # compile + flash (COM3)
    .\idf-build.ps1 -Upload -OutDir archive\v0.7.4
    .\idf-build.ps1 -Menuconfig      # browse the settings (writes idf\sdkconfig; copy changes to sdkconfig.defaults)
#>
param(
  [switch]$Upload,
  [string]$Port = "COM3",
  [string]$OutDir = "",
  [switch]$Menuconfig
)
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$proj = Join-Path $root "idf"

# exact source version -> build_info.h 
$describe = (git -C $root describe --tags --always --dirty 2>$null)
if (-not $describe) { $describe = "no-git" }
$info = "// Generated by idf-build.ps1 - do not edit, not versioned.`n#pragma once`n#define FW_GIT_DESCRIBE `"$describe`"`n"
[IO.File]::WriteAllText((Join-Path $root "firmware\build_info.h"), $info)
Write-Host "source: $describe (ESP-IDF build)"

$idfRoot = if ($env:IDF_PATH) { $env:IDF_PATH } else { "C:\esp\esp-idf-v5.5.4" }
. "$idfRoot\export.ps1" *> $null
Push-Location $proj
try {
  if ($Menuconfig) { idf.py menuconfig; return }
  $log = Join-Path $proj "build.log"
  idf.py build *> $log
  if ($LASTEXITCODE -ne 0) {
    Select-String -Path $log -Pattern "error:" | Select-Object -First 20 | ForEach-Object { Write-Host $_.Line }
    throw "compile failed (log: $log)"
  }
  # Fixed wording - validate.ps1 / ota.ps1 parse these two lines
  $size = (Get-Item "build\NAV1.bin").Length
  Write-Host ("firmware {0} bytes = {1} % of the 3 MB app slot" -f $size, [math]::Round(100 * $size / 3MB))
  $warn = @(Select-String -Path $log -Pattern "firmware[\\/][^:]+:\d+:\d+: warning:").Count
  Write-Host "project warnings: $warn"
  if ($OutDir) {
    $out = if ([IO.Path]::IsPathRooted($OutDir)) { $OutDir } else { Join-Path $root $OutDir }
    New-Item -ItemType Directory -Force $out | Out-Null
    Copy-Item "build\NAV1.bin", "build\NAV1.elf", "build\NAV1.map", "build\bootloader\bootloader.bin",
              "build\partition_table\partition-table.bin", "sdkconfig" $out -Force
  }
  if ($Upload) {
    idf.py -p $Port flash *> (Join-Path $proj "flash.log")
    if ($LASTEXITCODE -ne 0) { Get-Content (Join-Path $proj "flash.log") -Tail 15; throw "flash failed" }
    Write-Host "flashed $Port (hash of data verified)"
  }
} finally { Pop-Location }
