"""Builds the map label font (firmware/src/services/MapFontData.cpp) from a TrueType font.
usage: mapfont.py <font.ttf> [out.cpp]      needs ImageMagick (magick) for the anti-aliased glyph bitmaps

Glyph set: ASCII, Hebrew letters and punctuation, a few typographic marks. Two sizes (small: road names,
large: place names). Each glyph is stored as a 4-bit alpha bitmap; advances come from the font's hmtx table.
The font used for the committed data is Rubik (SIL OFL 1.1, (c) The Rubik Project Authors)."""
import struct, subprocess, sys, os

FONT = sys.argv[1]
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), '..', '..', 'firmware', 'src', 'services', 'MapFontData.cpp')
SIZES = [("SMALL", 13), ("LARGE", 17)]
CODES = sorted(set(list(range(0x20, 0x7F)) + list(range(0x05D0, 0x05EB)) + [0x05BE, 0x05F3, 0x05F4, 0x2013, 0x2019, 0x00B0]))

d = open(FONT, 'rb').read()
n = struct.unpack('>H', d[4:6])[0]
tab = {d[12 + 16 * i:16 + 16 * i].decode(): struct.unpack('>II', d[20 + 16 * i:28 + 16 * i]) for i in range(n)}

def u16(o): return struct.unpack('>H', d[o:o + 2])[0]
def s16(o): return struct.unpack('>h', d[o:o + 2])[0]
def u32(o): return struct.unpack('>I', d[o:o + 4])[0]

upm = u16(tab['head'][0] + 18)
hh = tab['hhea'][0]
ascent, descent, nhm = s16(hh + 4), s16(hh + 6), u16(hh + 34)
hmtx = tab['hmtx'][0]

def advance_units(gid):
    return u16(hmtx + 4 * min(gid, nhm - 1))

def cmap_lookup():
    o = tab['cmap'][0]
    cnt = u16(o + 2)
    best = None
    for i in range(cnt):
        pid, eid, off = u16(o + 4 + 8 * i), u16(o + 6 + 8 * i), u32(o + 8 + 8 * i)
        fmt = u16(o + off)
        if (pid, eid) in ((3, 1), (0, 3), (0, 4), (3, 10)) and fmt in (4, 12):
            if best is None or fmt == 12: best = (o + off, fmt)
    base, fmt = best
    m = {}
    if fmt == 4:
        segx2 = u16(base + 6)
        seg = segx2 // 2
        ends = base + 14
        starts = ends + segx2 + 2
        deltas = starts + segx2
        ranges = deltas + segx2
        for s in range(seg):
            e, st, dl, ro = u16(ends + 2 * s), u16(starts + 2 * s), s16(deltas + 2 * s), u16(ranges + 2 * s)
            for c in range(st, e + 1):
                if c == 0xFFFF: continue
                if ro == 0: g = (c + dl) & 0xFFFF
                else:
                    go = ranges + 2 * s + ro + 2 * (c - st)
                    g = u16(go)
                    if g: g = (g + dl) & 0xFFFF
                m[c] = g
    else:
        ng = u32(base + 12)
        for i in range(ng):
            st, en, g0 = u32(base + 16 + 12 * i), u32(base + 20 + 12 * i), u32(base + 24 + 12 * i)
            for c in range(st, en + 1): m[c] = g0 + c - st
    return m

cmap = cmap_lookup()

def render(cp, px):
    W = H = 64
    ox, oy = 16, 40
    ch = chr(cp)
    arg = ch.replace('\\', '\\\\').replace('"', '\\"')
    cmd = ["magick", "-size", f"{W}x{H}", "xc:black", "-font", FONT, "-pointsize", str(px), "-fill", "white",
           "-annotate", f"+{ox}+{oy}", ch, "-colorspace", "Gray", "-depth", "8", "gray:-"]
    raw = subprocess.run(cmd, capture_output=True, check=True).stdout
    if len(raw) != W * H: raise SystemExit("bad render for %04X" % cp)
    xs = [x for y in range(H) for x in range(W) if raw[y * W + x] > 8]
    ys = [y for y in range(H) for x in range(W) if raw[y * W + x] > 8]
    if not xs: return None
    x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
    w, h = x1 - x0 + 1, y1 - y0 + 1
    bits = bytearray(((w + 1) // 2) * h)
    for y in range(h):
        for x in range(w):
            a = raw[(y0 + y) * W + x0 + x] >> 4
            i = y * ((w + 1) // 2) + x // 2
            bits[i] |= a << (4 if x % 2 == 0 else 0)
    return dict(bx=x0 - ox, y0=y0, y1=y1, w=w, h=h, bits=bytes(bits))

out = ['// Generated by tools/scripts/mapfont.py from Rubik (SIL OFL 1.1, (c) The Rubik Project Authors). Do not edit.',
       '#include "MapFont.h"', '']
for name, px in SIZES:
    glyphs, blob = [], bytearray()
    baseline = 40                                       # annotate puts the pen baseline at y = 40 of the render canvas
    for cp in CODES:
        gid = cmap.get(cp, 0)
        if gid == 0 and cp != 0x20: continue
        adv = round(advance_units(gid) * px / upm)
        g = render(cp, px) if cp != 0x20 else None
        if g is None:
            glyphs.append((cp, 0, 0, 0, 0, adv, len(blob)))
        else:
            glyphs.append((cp, g['bx'], baseline - g['y0'], g['w'], g['h'], adv, len(blob)))
            blob += g['bits']
    out.append(f'static const uint8_t BITS_{name}[] = {{')
    for i in range(0, len(blob), 24):
        out.append('  ' + ','.join('0x%02X' % b for b in blob[i:i + 24]) + ',')
    out.append('};')
    out.append(f'static const MapGlyph GLY_{name}[] = {{')
    for g in glyphs:
        out.append('  { 0x%04X, %d, %d, %d, %d, %d, %d },' % g)
    out.append('};')
    asc = round(ascent * px / upm)
    out.append(f'const MapFont MAPFONT_{name} = {{ {px}, {asc}, {round((ascent - descent) * px / upm)}, GLY_{name}, {len(glyphs)}, BITS_{name} }};')
    out.append('')
    print(name, px, len(glyphs), 'glyphs', len(blob), 'bytes')
open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('written', OUT)
