"""Builds the extra UI fonts in firmware/src/ui from TrueType fonts:
  FontHe20.c, FontHe28.c   Hebrew letters for labels that show names (places, destinations)
  FontDigits120.c          the speed on the Drive dashboard (digits only)
usage: uifont.py <hebrew.ttf> <digits.ttf>        needs lv_font_conv 1.5.x (npm install -g lv_font_conv)

The fonts hold only the Hebrew letters (and maqaf, geresh, gershayim); every other character falls back to the
built-in Montserrat of the same size, so Latin text keeps its look and labels can mix both scripts. Line height
and baseline are copied from Montserrat so a label is laid out exactly as before. Text has to be in visual order
(ui/Bidi.h): LVGL's own bidi support is off.
The committed fonts are made from Rubik Medium (SIL OFL 1.1, (c) The Rubik Project Authors), the font of the map
labels: python -m fontTools.varLib.instancer Rubik[wght].ttf wght=500 -o Rubik-Medium.ttf
The digits come from Montserrat Medium (SIL OFL 1.1), the family of LVGL's built-in fonts, made the same way."""
import os, re, subprocess, sys

HEBREW, DIGITS = sys.argv[1], sys.argv[2]
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'firmware', 'src', 'ui')
MONTSERRAT = {20: (22, 4), 28: (30, 5)}          # line_height, base_line of LVGL's lv_font_montserrat_<size>


def build(font, rng, size, name, out, fallback=None, metrics=None):
    tmp = os.path.join(OUT, name + '.tmp.c')
    cmd = ['lv_font_conv', '--font', font, '-r', rng, '--size', str(size), '--bpp', '4', '--format', 'lvgl',
           '--lv-font-name', name, '--no-compress', '-o', tmp]
    if fallback: cmd += ['--lv-fallback', fallback]
    subprocess.run(cmd, check=True, shell=os.name == 'nt')
    c = open(tmp, encoding='utf-8').read()
    os.remove(tmp)
    c = re.sub(r' \* Opts: .*\n', ' * Generated by tools/scripts/uifont.py - do not edit.\n', c)
    c = re.sub(r'#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n#include "lvgl.h"\n#else\n#include "lvgl/lvgl.h"\n#endif', '#include <lvgl.h>', c)
    c = c.replace('LV_VERSION_CHECK(7, 4, 0) || ', '').replace('LV_VERSION_CHECK(8, 2, 0) || ', '')
    if metrics:
        c = re.sub(r'\.line_height = \d+,', '.line_height = %d,' % metrics[0], c)
        c = re.sub(r'\.base_line = \d+,', '.base_line = %d,' % metrics[1], c)
    open(os.path.join(OUT, out), 'w', encoding='utf-8', newline='\n').write(c)
    print(out)


for size, m in MONTSERRAT.items():
    build(HEBREW, '0x5BE,0x5D0-0x5EA,0x5F3-0x5F4', size, 'nav_he_%d' % size, 'FontHe%d.c' % size, 'lv_font_montserrat_%d' % size, m)
build(DIGITS, '0x20,0x2D-0x2E,0x30-0x3A', 120, 'nav_digits_120', 'FontDigits120.c')
