// =============================================================================
//  MapFont  -  small bitmap fonts for the map labels (street and place names, Hebrew and Latin).
//  Data: MapFontData.cpp, generated by tools/scripts/mapfont.py from Rubik (SIL OFL 1.1). Glyphs are 4-bit
//  alpha bitmaps; everything is const data in flash, so the map renderer task can read it freely.
// =============================================================================
#pragma once

#include <stdint.h>

struct MapGlyph {
  uint16_t cp;          // Unicode code point
  int8_t bx, by;        // bitmap left edge from the pen, bitmap top edge above the baseline (pixels)
  uint8_t w, h;         // bitmap size (0 = no ink, e.g. space)
  uint8_t adv;          // advance
  uint16_t off;         // offset into the bitmap array (rows of (w + 1) / 2 bytes, high nibble first)
};

struct MapFont {
  uint8_t size, ascent, line;
  const MapGlyph *glyphs;
  uint16_t count;
  const uint8_t *bits;
};

extern const MapFont MAPFONT_SMALL, MAPFONT_LARGE;

namespace MapText {
  struct Run {                          // a laid-out label: glyph indices in visual (left to right) order
    const MapGlyph *g[48];
    int n = 0;
    int width = 0;                      // sum of the advances
  };
  // UTF-8 -> glyphs in visual order (Hebrew right to left, digits / Latin left to right). false = a character
  // the font does not have, or too long: the label is not drawn.
  bool layout(const MapFont &f, const uint8_t *utf8, int len, Run &out);
}
