// =============================================================================
//  UiText  -  names in the UI (places, destinations): Hebrew and Latin in one label.
// -----------------------------------------------------------------------------
//  LVGL's own bidi support is off (it would cost every label). Labels that show a name use the
//  nav_he_* fonts: Hebrew letters from Rubik, every other character from the built-in Montserrat of
//  the same size (font fallback), and get their text through visual(): Hebrew runs reversed, Latin
//  and digits kept left to right - the same rule as the map labels (services/MapFont.cpp).
//  Fonts: ui/FontHe20.c, FontHe28.c, FontDigits120.c, generated by tools/scripts/uifont.py.
// =============================================================================
#pragma once

#include <lvgl.h>
#include <stddef.h>

extern "C" {
extern const lv_font_t nav_he_20;        // Montserrat 20 + Hebrew
extern const lv_font_t nav_he_28;        // Montserrat 28 + Hebrew
extern const lv_font_t nav_digits_120;   // digits, '.', '-', ':' and space only (Drive speed)
}

namespace UiText {
  // UTF-8 in logical (typed) order -> visual order, left to right. `out` is always terminated.
  void visual(const char *in, char *out, size_t cap);
  // label text = visual(utf8); only redrawn when it changed
  void setName(lv_obj_t *label, const char *utf8);
  bool isAscii(const char *s);
}
